// Archival link:
// https://web.archive.org/web/20140212174237/http://www.mknepprath.com/my-only-suggestion-for-facebook-paper/

// TODO: Check accuracy of timestamp.

import Image from "next/image";

import BlogPage from "core/blog-page";

export const meta = {
  published: true,
  publishedAt: "2014-02-12",
  title: "My Only Suggestion For Facebook Paper",
};

export default function FacebookPaper(): React.ReactNode {
  return (
    <BlogPage dateTime={meta.publishedAt} title={meta.title}>
      <header>
        <h1>{meta.title}</h1>
      </header>

      <p>
        First of all, great job to{" "}
        <a href="https://twitter.com/mike_matas">Mike Matas</a> and his team.
        This new Facebook experience is a joy to use.
      </p>
      <p>
        I do have one gripe with it, however, and I only bring it up because I
        feel that the solution is obvious and a missed opportunity. Allow me to
        introduce Facebook lists:
      </p>

      <Image
        alt="Facebook lists"
        className="corner-radius-8"
        height={960}
        layout="responsive"
        priority
        src="/assets/facebook-paper-lists.png"
        width={1190}
      />

      <p>Facebook lists are powerful, and here’s why:</p>
      <ol>
        <li>
          When you create a list, you have the ability to view it as a Newsfeed
          containing posts exclusively by the people you chose to be in that
          list.
        </li>
        <li>
          You can
          <a href="http://www.mknepprath.com/wp-content/uploads/2014/02/Screen-Shot-2014-02-12-at-8.47.19-AM.png">
            {" "}
            save lists to your favorites section
          </a>{" "}
          for easy access.
        </li>
        <li>
          You can choose to share a post with only the people in a certain list.
        </li>
        <li>
          Finally, Facebook already dynamically generates lists for you (called
          Smart Lists) based on employment, location, school, and family. With
          those, most of the work is done for you already.
        </li>
      </ol>
      <p>
        The one problem with Facebook lists? It’s a power user feature that
        normal people do not use. I believe it is for this reason that lists
        weren’t even included in Facebook Paper. And here’s where Facebook Paper
        comes in.
      </p>
      <p>
        Facebook Paper is largely a re-imagining of the current Facebook
        experience, but does include something new: Sections.
      </p>

      <Image
        alt="Facebook Paper sections"
        className="corner-radius-8"
        height={533}
        src="/assets/facebook-paper-sections.png"
        layout="responsive"
        width={900}
      />

      <p>
        If you swipe to the right on the featured post (“Movie night!” depicted
        above), it takes you to new Newsfeeds (such as Tech, Pop Life, Score,
        Headlines) containing curated news content. You don’t have control over
        what appears in these sections, these were pre-decided by Facebook
        through agreements they’ve made with certain content providers. The one
        problem with Facebook Sections? I don’t need a new source of news, and I
        don’t find this source to be as easily digestible as others (such as
        Twitter).
      </p>
      <p>
        Do you see where I’m going with this?{" "}
        <b>Facebook Paper Sections should be Facebook lists.</b> And here are
        the reasons I find it particularly obvious:
      </p>
      <ol>
        <li>
          When swiping to the right of your main Newsfeed, it makes sense that
          you would find alternate Newsfeeds. This already exists with Facebook
          lists.
        </li>
        <li>
          Typically, the problem with implementing something like this is that
          users would have to go through the process of creating these alternate
          lists. This has already been taken care of with Smart Lists. They have
          a set of default lists, dynamically generated by Facebook.
        </li>
        <li>
          Facebook Paper is an experiment, giving them room to play with new
          ways of letting users create and manage lists.
        </li>
      </ol>
      <p>
        Not a single service has figured out how to get lists to work. Google
        came closest with Circles on Google+, but lists on Facebook and Twitter
        are both duds thus far. Facebook Paper gives Facebook an opportunity to
        make lists work by easing users into using them first, then introducing
        the more useful and powerful features as needed.
      </p>
      <p>
        <b>Bonus read:</b>{" "}
        <a href="https://brianlovin.com/design-details/paper-facebook-ios">
          Design Details: Paper by Facebook
        </a>{" "}
        by Brian Lovin
      </p>
    </BlogPage>
  );
}
